security:
    encoders:
        App\Entity\User:
            algorithm: 'bcrypt'
            cost: 12
        App\Entity\UserAdmin:
            algorithm: 'bcrypt'
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_user_admin_provider:
            entity:
                class: App\Entity\UserAdmin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        login_admin:
            pattern: ^/admin/login
            stateless: true
            anonymous: true
            provider: app_user_admin_provider
            json_login:
                check_path: /admin/login_admin_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        
        api_admin:
            pattern: ^/admin
            stateless: true
            anonymous: true
            provider: app_user_admin_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_admin_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }